# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f396d98c2c7f5b705aab5169cc9b5d7644b733b767514ec426c65226eac273d3bdf335800399e3a7919561f6b047ba864252847e6d0a41e350dd1933dc8182e5

test:
  secret_key_base: ff1ca772f3c225e5c53a43460cfb39af91f53dcceb6854861f4c99333566f40a734b3e53ab7f6bb9753586588690db82bad39d2a9714e575f3339ee4e28e0558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
